version: '3.8'

services:
  carworkshop:
    build:
      context: .
      dockerfile: Dockerfile
    image: carworkshop:latest
    ports:
      - "5001:5001"

  nginx:
    image: nginx:latest
    ports:
      - "7000:7000"  
      - "443:443"  
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  
      - ./certs:/etc/nginx/ssl  
    depends_on:
      - carworkshop